---
abstract: 'RunScript trait to encode values in DBIx::Class::Migration::RunScript'
author:
  - 'John Napiorkowski <jjnapiork@cpan.org>'
build_requires:
  DBIx::Class: 0
  DBIx::Class::Migration: 0.033
  DBIx::Class::PassphraseColumn: 0
  File::Path: 0
  File::Spec::Functions: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-Migration-RunScript-Trait-AuthenPassphrase
requires:
  Authen::Passphrase: 0
  Class::Load: 0
  Moose: 0
resources:
  bugtracker: https://github.com/jjn1056/DBIx-Class-Migration-RunScript-Trait-AuthenPassphrase/issues
  homepage: https://github.com/jjn1056/DBIx-Class-Migration-RunScript-Trait-AuthenPassphrase
  repository: https://github.com/jjn1056/DBIx-Class-Migration-RunScript-Trait-AuthenPassphrase.git
version: 0.001
